### ISSUE TITLE
Automatic setting of labels fails with 404

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena-plugin-upcloud#27]
Creating nodes end up hitting 404 on server api while setting labels:
```
E, [2017-10-30T11:09:03.117351 #17123] ERROR -- CLI: Not found (/v1/nodes/prod/prod/strong-cloud-12) (Kontena::Errors::StandardError)
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/client.rb:537:in `handle_error_response'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/client.rb:343:in `rescue in request'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/client.rb:284:in `request'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/client.rb:219:in `put'
/Users/foo/.kontena/gems/2.4.2/gems/kontena-plugin-upcloud-0.3.1/lib/kontena/machine/upcloud/node_provisioner.rb:114:in `set_labels'
/Users/foo/.kontena/gems/2.4.2/gems/kontena-plugin-upcloud-0.3.1/lib/kontena/machine/upcloud/node_provisioner.rb:91:in `block in run!'
/Users/foo/.kontena/gems/2.4.2/gems/kontena-plugin-upcloud-0.3.1/lib/kontena/machine/upcloud/node_provisioner.rb:36:in `times'
/Users/foo/.kontena/gems/2.4.2/gems/kontena-plugin-upcloud-0.3.1/lib/kontena/machine/upcloud/node_provisioner.rb:36:in `run!'
/Users/foo/.kontena/gems/2.4.2/gems/kontena-plugin-upcloud-0.3.1/lib/kontena/plugin/upcloud/nodes/create_command.rb:23:in `execute'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/usr/local/Cellar/kontena/1.4.0/libexec/gems/kontena-cli-1.4.0/bin/kontena:18:in `<top (required)>'
/usr/local/Cellar/kontena/1.4.0/libexec/bin/kontena:23:in `load'
/usr/local/Cellar/kontena/1.4.0/libexec/bin/kontena:23:in `<main>'
```

https://github.com/kontena/kontena-plugin-upcloud/blob/master/lib/kontena/machine/upcloud/node_provisioner.rb#L114

So for a grid named `prod`, it ends up "duplicating" the grid name in the node identifier in the URL.

**Comment by SpComb** [comment]
Looks like the packet plugin is the exception to the rule re https://github.com/kontena/kontena/pull/2483

The other plugins used the legacy `nodes/#{node['id']}` API with the `Kontena-Token` header, which still just barely works with the changes in #2483. The `nodes/#{node['grid']['id']}/#{node['id']}` here doesn't, it needs to be changed to `nodes/#{node['id']}` for 1.4, although that won't work with 1.3 unless you also supply the `Kontena-Token` header for the legacy API.
